site.title: Tutorials for Apache Karaf
theme: jekyll-theme-cayman
plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
avatar: https://avatars1.githubusercontent.com/u/484584?s=96
